### ISSUE TITLE
Add option to disable Swiftclick on a per element basis

### ISSUE THREAD

**Issue by mrmartineau** [munkychop/swiftclick#2]
Is is possible to do this? I am using the Flickity carousel by Metafizzy and this conflicts.

Feature request?

**Comment by munkychop** [comment]
Yes, in fact this is something I've been thinking about adding, as the same behaviour is exhibited when using Google Maps, and other libraries that implement their own touch-to-click event conversion.

My only reservation is that this addition could bloat the code-base. I'll look into it when I have some spare time.

**Comment by munkychop** [comment]
@mrmartineau This has now been implemented in [release 1.2.0](https://github.com/munkychop/swiftclick/releases/tag/1.2.0) (1686eb1).
Also published to npm :smile:

**Comment by mrmartineau** [comment]
Yes! :+1: :100:
