### ISSUE TITLE
Causes issues while handling touch events on an element which has SwiftClick tracked children.

### ISSUE THREAD

**Issue by prashantpalikhe** [munkychop/swiftclick#3]
`touchEndHandler` of SwiftClick is stopping propagation of the event. So, if we are handling touch events on a parent and a SwiftClick handled element is the event target, the touch event will never reach the parent. 

https://github.com/munkychop/swiftclick/blob/master/js/libs/swiftclick.js#L117

Example scenario:

We have a drawer element which can be swiped in and out of the viewport. Drawer has links inside which are SwiftClick managed. When we drag the drawer by placing the finger over a link and let the finger go, SwiftClick's `touchEndHandler` kicks in, stops the propagation and the drawer's touch end handler never gets invoked.

PS `stopPropagation()` was introduced to prevent ghost clicks on Android devices. But we no longer need SwiftClick for Android.

**Comment by munkychop** [comment]
@prashantpalikhe thanks for the report. Would you be able to create a simplified example of this behaviour?

**Comment by prashantpalikhe** [comment]
Sure! Here is the bin

https://jsbin.com/roqumuyena/1/

Steps to reproduce:

1. Enable Chrome device emulation.
2. Select a device e.g. iPhone
3. Drag the box with your touch target over the text.
4. The box follows the cursor.
5. Release the finger.
6. The box snaps back to its original position.
5. Enable SwiftClick
6. Drag the box again and release the finger.
7. The box does not snap back.

**Comment by munkychop** [comment]
@prashantpalikhe thanks very much for the example. I'll investigate this when I get the time.

**Comment by prashantpalikhe** [comment]
@munkychop Any estimation on when you can look into this? Or, if we create a PR for you, how long before you can test the PR and have it merged?

**Comment by munkychop** [comment]
@prashantpalikhe I'll hopefully be able to do a little bit of work on this tomorrow, otherwise it's likely to be some time next week.

Feel free to submit a PR, ensuring that it doesn't break the experience for Android devices.

Cheers

**Comment by prashantpalikhe** [comment]
Is there a need to stop the propagation of touch event if the touch is more like a drag?

https://github.com/munkychop/swiftclick/blob/master/js/libs/swiftclick.js#L117

What's the need to cancel the touch at all for that matter? Logically, it does not make much sense to me to cancel the touchend just because the touch moved beyond the threshold.

As long as, the synthetic click event is not fired, it should be good right?

But according to the commit history, it was done to prevent Android ghost clicks. Is there a way to reproduce this ghost click scenario?

**Comment by munkychop** [comment]
Fixed by https://github.com/munkychop/swiftclick/pull/4
(thanks @prashantpalikhe :thumbsup:)
